import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { Spotlight } from "@/components/ui/spotlight";


const poppins = Montserrat({
    weight: ["400", "500", "600"],
    display: "swap",
    subsets: ["latin"],
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section className={'overflow-hidden flex items-center justify-center min-h-screen h-full '}>
            <div className='pb-20 pt-36'>
                <Spotlight className='-top-40 -left-10 md:-left-32 md:-top-20 h-screen' fill='white' />
                <Spotlight className='-top-10 -left-full h-[80vh] w-[50vw]' fill='purple' />
                <Spotlight className='-top-28 left-80 h-[80vh] w-[50vw]' fill='blue' />
            </div>
            <div className="h-screen w-full bg-black-100 bg-grid-white/[0.03] flex items-center justify-center absolute  top-0 left-0">
                <div className="absolute pointer-events-none inset-0 flex items-center justify-center bg-black-100 [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]" />
            </div>
            {children}
        </section>
    );
}
