import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";


const poppins = Montserrat({
    weight: ["400", "500", "600"],
    display: "swap",
    subsets: ["latin"],
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section className={'overflow-hidden flex items-center justify-center min-h-screen h-full'}>
            {children}
        </section>
    );
}
